/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'
import { Route as ShellPatternInvestigatorRouteImport } from './routes/_shell.pattern-investigator'
import { Route as ShellLiveGuardRouteImport } from './routes/_shell.live-guard'
import { Route as ShellIdentityVaultRouteImport } from './routes/_shell.identity-vault'
import { Route as ShellCommandCentreRouteImport } from './routes/_shell.command-centre'
import { Route as ShellAuditIntelligenceRouteImport } from './routes/_shell.audit-intelligence'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPatternInvestigatorRoute =
  ShellPatternInvestigatorRouteImport.update({
    id: '/pattern-investigator',
    path: '/pattern-investigator',
    getParentRoute: () => ShellRoute,
  } as any)
const ShellLiveGuardRoute = ShellLiveGuardRouteImport.update({
  id: '/live-guard',
  path: '/live-guard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellIdentityVaultRoute = ShellIdentityVaultRouteImport.update({
  id: '/identity-vault',
  path: '/identity-vault',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCommandCentreRoute = ShellCommandCentreRouteImport.update({
  id: '/command-centre',
  path: '/command-centre',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAuditIntelligenceRoute = ShellAuditIntelligenceRouteImport.update({
  id: '/audit-intelligence',
  path: '/audit-intelligence',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-intelligence': typeof ShellAuditIntelligenceRoute
  '/command-centre': typeof ShellCommandCentreRoute
  '/identity-vault': typeof ShellIdentityVaultRoute
  '/live-guard': typeof ShellLiveGuardRoute
  '/pattern-investigator': typeof ShellPatternInvestigatorRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-intelligence': typeof ShellAuditIntelligenceRoute
  '/command-centre': typeof ShellCommandCentreRoute
  '/identity-vault': typeof ShellIdentityVaultRoute
  '/live-guard': typeof ShellLiveGuardRoute
  '/pattern-investigator': typeof ShellPatternInvestigatorRoute
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/audit-intelligence': typeof ShellAuditIntelligenceRoute
  '/_shell/command-centre': typeof ShellCommandCentreRoute
  '/_shell/identity-vault': typeof ShellIdentityVaultRoute
  '/_shell/live-guard': typeof ShellLiveGuardRoute
  '/_shell/pattern-investigator': typeof ShellPatternInvestigatorRoute
  '/_shell/settings': typeof ShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-intelligence'
    | '/command-centre'
    | '/identity-vault'
    | '/live-guard'
    | '/pattern-investigator'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-intelligence'
    | '/command-centre'
    | '/identity-vault'
    | '/live-guard'
    | '/pattern-investigator'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/audit-intelligence'
    | '/_shell/command-centre'
    | '/_shell/identity-vault'
    | '/_shell/live-guard'
    | '/_shell/pattern-investigator'
    | '/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pattern-investigator': {
      id: '/_shell/pattern-investigator'
      path: '/pattern-investigator'
      fullPath: '/pattern-investigator'
      preLoaderRoute: typeof ShellPatternInvestigatorRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/live-guard': {
      id: '/_shell/live-guard'
      path: '/live-guard'
      fullPath: '/live-guard'
      preLoaderRoute: typeof ShellLiveGuardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/identity-vault': {
      id: '/_shell/identity-vault'
      path: '/identity-vault'
      fullPath: '/identity-vault'
      preLoaderRoute: typeof ShellIdentityVaultRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/command-centre': {
      id: '/_shell/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof ShellCommandCentreRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/audit-intelligence': {
      id: '/_shell/audit-intelligence'
      path: '/audit-intelligence'
      fullPath: '/audit-intelligence'
      preLoaderRoute: typeof ShellAuditIntelligenceRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAuditIntelligenceRoute: typeof ShellAuditIntelligenceRoute
  ShellCommandCentreRoute: typeof ShellCommandCentreRoute
  ShellIdentityVaultRoute: typeof ShellIdentityVaultRoute
  ShellLiveGuardRoute: typeof ShellLiveGuardRoute
  ShellPatternInvestigatorRoute: typeof ShellPatternInvestigatorRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAuditIntelligenceRoute: ShellAuditIntelligenceRoute,
  ShellCommandCentreRoute: ShellCommandCentreRoute,
  ShellIdentityVaultRoute: ShellIdentityVaultRoute,
  ShellLiveGuardRoute: ShellLiveGuardRoute,
  ShellPatternInvestigatorRoute: ShellPatternInvestigatorRoute,
  ShellSettingsRoute: ShellSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
